package com.allterra.presentation.localization

import com.allterra.domain.model.AppLanguage

data class AppStrings(
    val appName: String,
    val appTagline: String,
    val appFooter: String,
    val loginTitle: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val nameLabel: String,
    val emailLabel: String,
    val passwordLabel: String,
    val loginAction: String,
    val registerAction: String,
    val registerLink: String,
    val loginLink: String,
    val languageLabel: String,
    val loadingText: String,
    val authFieldValidation: String,
    val authSuccess: String,
    val logoutAction: String,
    val feedHeaderUser: String,
    val aboutTitle: String,
    val aboutPlaceholder: String,
    val profileName: String,
    val profileAbout: String,
    val tabRoutes: String,
    val tabProfile: String,
    val tabMap: String,
    val tabFeed: String,
    val tabSettings: String,
    val poisTitle: String,
    val routesTitle: String,
    val mapTitle: String,
    val feedTitle: String,
    val feedEmptyTitle: String,
    val feedEmptyBody: String,
    val feedLoadMoreAction: String,
    val feedTabAll: String,
    val feedTabFriends: String,
    val feedTabClubs: String,
    val feedTabDiscover: String,
    val feedChipAllActivities: String,
    val feedChipHike: String,
    val feedChipBikepacking: String,
    val feedChipClimb: String,
    val feedNearbyAuthorsLabel: String,
    val feedOpenMapAction: String,
    val walletFeatureTitle: String = "Wallet",
    val walletFeatureDesc: String = "Tickets, bookings",
    val routesFeatureTitle: String = "Routes",
    val routesFeatureDesc: String = "Map, GPX, topo",
    val gearFeatureTitle: String = "Gear",
    val gearFeatureDesc: String = "Packing lists, inventory",
    val sharingFeatureTitle: String = "Sharing",
    val sharingFeatureDesc: String = "Group sync",
    val addedLabel: String,
    val updatedLabel: String,
    val importRouteTitle: String,
    val importRouteBody: String,
    val importSampleAction: String,
    val importGpxAction: String,
    val addEmptyRouteAction: String,
    val cancelAction: String,
    val poiNewTitle: String,
    val routeNewTitle: String,
    val routeCreateTitle: String,
    val routeTitleLabel: String,
    val routeDescriptionLabel: String,
    val routeGpxLabel: String,
    val routeNoFileSelected: String,
    val routeImportFailed: String,
    val routeCreationValidation: String,
    val routeUploadingLabel: String,
    val routeProcessingLabel: String,
    val routePreviewTitle: String,
    val routeDistanceLabel: String,
    val routeDurationLabel: String,
    val routePointsLabel: String,
    val poiCreateTitle: String,
    val poiNameLabel: String,
    val poiTypeLabel: String,
    val poiCreationValidation: String,
    val poiTypeShop: String,
    val poiTypeParking: String,
    val poiTypeCamping: String,
    val poiTypeWater: String,
    val poiTypeOther: String,
    val addPhotosAction: String,
    val poiNoPhotosSelected: String,
    val poiPhotosHint: String,
    val poiPhotoLimitReached: String,
    val poiPhotoReadError: String,
    val postCreateTitle: String,
    val postTitleLabel: String,
    val postDescriptionLabel: String,
    val postAudienceLabel: String,
    val postAudiencePublic: String,
    val postAudienceFriends: String,
    val postAudienceClub: String,
    val postTripLabel: String,
    val postNoTrips: String,
    val postRouteLabel: String,
    val postNoRoutes: String,
    val postPoisLabel: String,
    val postNoPois: String,
    val postCreationValidation: String,
    val photosLabel: String,
    val photosHint: String,
    val postNoPhotosSelected: String,
    val postPhotosHint: String,
    val postPhotoLimitReached: String,
    val postPhotoReadError: String,
    val noneLabel: String,
    val saveAction: String,
    val deleteAction: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val cardMore: String,
    val settingsPlaceholderTitle: String,
    val settingsPlaceholderBody: String,
    val settingsDisplaySection: String = "Display",
    val settingsLanguageLabel: String = "Language",
    val settingsThemeLabel: String = "Theme",
    val settingsThemeLight: String = "Light",
    val settingsThemeDark: String = "Dark",
    val settingsThemeSystem: String = "System",
    val settingsNotificationsSection: String = "Notifications",
    val settingsPrivacySection: String = "Privacy",
    val settingsAccountSection: String = "Account",
    val settingsAboutSection: String = "About",
    val settingsVersionLabel: String = "Version",
    val wardrobeAction: String,
    val journalAllFilter: String,
    val journalTripFilter: String,
    val journalStandaloneFilter: String,
    val journalEmptyTitle: String,
    val journalEmptyBody: String,
    val feedSearchPlaceholder: String = "Search posts",
    val notificationsTitle: String = "Notifications",
    val notificationsEmptyTitle: String = "No notifications yet",
    val notificationsEmptyBody: String = "Post activity and system events will appear here.",
    val tabHome: String = "Home",
    val tabWallet: String = "Wallet",
    val tabTrips: String = "Trips",
    val onboardingTitle: String = "Welcome to Allterra",
    val onboardingSubtitle: String = "A traveler's wallet for every trip.",
    val onboardingStartAction: String = "Get started",
    val onboardingSkipAction: String = "Skip",
    val onboardingNextAction: String = "Next",
    val onboardingFinishAction: String = "Finish",
    val onboardingWalletTitle: String = "Travel Wallet",
    val onboardingWalletBody: String = "Aggregate PDFs, tickets, bookings, and insurance in one secure place.",
    val onboardingMapTitle: String = "Offline Maps",
    val onboardingMapBody: String = "Keep routes, waypoints, and elevation profiles ready for the trail.",
    val onboardingGearTitle: String = "Gear Tracking",
    val onboardingGearBody: String = "Manage equipment, packing, and wear before every outing.",
    val onboardingSocialTitle: String = "Share the Journey",
    val onboardingSocialBody: String = "Coordinate with friends and keep the whole group in sync.",
    val dashboardGreetingPrefix: String = "Hello",
    val dashboardGreetingBody: String = "Ready for the next adventure?",
    val dashboardUpcomingTrip: String = "Upcoming Trip",
    val dashboardPackingProgress: String = "Packing progress",
    val dashboardQuickActions: String = "Quick Actions",
    val dashboardRecentTrips: String = "Recent Trips",
    val dashboardSeeAll: String = "See all",
    val dashboardPackingAction: String = "Packing",
    val dashboardNewPostAction: String = "New Post",
    val dashboardAddDocAction: String = "Add Doc",
    val dashboardEmptyStateChip: String = "No trip",
    val dashboardNoUpcomingTripTitle: String = "No upcoming trip yet",
    val dashboardNoUpcomingTripBody: String = "Create or import a trip to see readiness, documents, and route status here.",
    val dashboardNoRecentTripsTitle: String = "No recent trips",
    val dashboardNoRecentTripsBody: String = "Completed trips will appear here after they are saved.",
    val walletTitle: String = "Travel Wallet",
    val walletOfflineStatus: String = "Offline",
    val walletTicketsGroup: String = "Active Tickets",
    val walletBookingsGroup: String = "Bookings",
    val walletInsuranceGroup: String = "Insurance",
    val walletOtherGroup: String = "Other Documents",
    val walletAddTitle: String = "Add to Wallet",
    val walletImportPdf: String = "PDF",
    val walletImportPhoto: String = "Photo",
    val walletImportEmail: String = "Email",
    val walletImportScan: String = "Scan",
    val walletImportManual: String = "Manual",
    val walletImportPass: String = "Wallet",
    val walletOpenPdf: String = "Open PDF",
    val walletEmptyTitle: String = "No wallet documents yet",
    val walletEmptyBody: String = "Import a PDF, photo, email, scan, or wallet pass to keep it available offline.",
    val walletEmptyAction: String = "Add document",
    val tripsEmptyPlannedTitle: String = "No planned trips",
    val tripsEmptyPlannedBody: String = "Create or import a trip to see route, wallet, gear, and notes here.",
    val tripsEmptyActiveTitle: String = "No active trips",
    val tripsEmptyActiveBody: String = "Active trips will appear here when a saved trip is started.",
    val tripsEmptyDoneTitle: String = "No completed trips",
    val tripsEmptyDoneBody: String = "Completed trips will appear here after they are saved.",
    val tripsCreateAction: String = "Create trip",
    val shareAction: String = "Share",
    val dateLabel: String = "Date",
    val timeLabel: String = "Time",
    val locationLabel: String = "Location",
    val postNewSubtitle: String = "in your feed",
    val postTypeLabel: String = "TYPE",
    val postTypeCheckIn: String = "Check-in",
    val postTypeRoute: String = "Route",
    val postTypeNote: String = "Note",
    val postTypeGear: String = "Gear",
    val postPhotoUploadTitle: String = "Add photo or cover",
    val postPhotoUploadLimit: String = "jpg, heic · up to 9",
    val postLocationPlaceholder: String = "Where are you now?",
    val postBodyPlaceholder: String = "Tell how it was...",
    val postActivityLabel: String = "ACTIVITY",
    val postPublishAction: String = "Publish",
    val feedFilterTitle: String = "Filters",
    val feedFilterClear: String = "Clear",
    val feedPostTripLabel: String = "Trip",
    val feedPostRouteLabel: String = "Route",
    val feedChipTrek: String = "Trek",
    val feedChipClimbing: String = "Climbing",
    val postLinkedItemLabel: String = "Location",
    val postNoCommentsTitle: String = "No comments yet",
    val postNoCommentsBody: String = "Be the first to share your thoughts!",
)

fun stringsFor(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.EN -> AppStrings(
            appName = "Allterra",
            appTagline = "A traveler's wallet — everything you need\nin the mountains, in one place",
            appFooter = "Allterra App ©",
            loginTitle = "Welcome back",
            registerTitle = "New User Registration",
            registerSubtitle = "Let's start your journey",
            nameLabel = "Name",
            emailLabel = "Email",
            passwordLabel = "Password",
            loginAction = "Login",
            registerAction = "Register",
            registerLink = "Register",
            loginLink = "Back to login",
            languageLabel = "English",
            loadingText = "Loading your outdoor world...",
            authFieldValidation = "Fill all required fields",
            authSuccess = "Success. Redirecting...",
            logoutAction = "Logout",
            feedHeaderUser = "UserName",
            aboutTitle = "About",
            aboutPlaceholder = "Love travel, hiking and bikepacking",
            profileName = "User Name",
            profileAbout = "Love travel, hiking and bikepacking",
            tabRoutes = "Routes",
            tabProfile = "Profile",
            tabMap = "Map",
            tabFeed = "Feed",
            tabSettings = "Settings",
            poisTitle = "POIs",
            routesTitle = "Routes",
            mapTitle = "Map",
            feedTitle = "Feed",
            feedEmptyTitle = "No posts in the feed yet",
            feedEmptyBody = "Create the first trail update or pull to refresh after your friends publish.",
            feedLoadMoreAction = "Load more",
            feedTabAll = "All",
            feedTabFriends = "Friends",
            feedTabClubs = "Clubs",
            feedTabDiscover = "Discover",
            feedChipAllActivities = "All activities",
            feedChipHike = "Hike",
            feedChipBikepacking = "Bikepacking",
            feedChipClimb = "Climb",
            feedNearbyAuthorsLabel = "authors nearby",
            feedOpenMapAction = "Open map",
            walletFeatureTitle = "Wallet",
            walletFeatureDesc = "Tickets, bookings",
            routesFeatureTitle = "Routes",
            routesFeatureDesc = "Map, GPX, topo",
            gearFeatureTitle = "Gear",
            gearFeatureDesc = "Packing lists, inventory",
            sharingFeatureTitle = "Sharing",
            sharingFeatureDesc = "Group sync",
            addedLabel = "Added",
            updatedLabel = "Updated",
            importRouteTitle = "Import Route",
            importRouteBody = "Choose a source to add route into your list",
            importSampleAction = "Import GPX",
            importGpxAction = "Import GPX",
            addEmptyRouteAction = "Add empty route",
            cancelAction = "Cancel",
            poiNewTitle = "New POI",
            routeNewTitle = "New Route",
            routeCreateTitle = "Create Route",
            routeTitleLabel = "Route title",
            routeDescriptionLabel = "Description",
            routeGpxLabel = "GPX file",
            routeNoFileSelected = "No file selected",
            routeImportFailed = "Failed to read GPX file",
            routeCreationValidation = "Import a valid GPX track with at least 2 track points",
            routeUploadingLabel = "Uploading GPX file...",
            routeProcessingLabel = "Parsing route on server...",
            routePreviewTitle = "Route preview",
            routeDistanceLabel = "Distance",
            routeDurationLabel = "Duration",
            routePointsLabel = "Points",
            poiCreateTitle = "Create POI",
            poiNameLabel = "POI name",
            poiTypeLabel = "Type",
            poiCreationValidation = "Enter POI name",
            poiTypeShop = "Shop",
            poiTypeParking = "Parking",
            poiTypeCamping = "Camping",
            poiTypeWater = "Water source",
            poiTypeOther = "Other",
            addPhotosAction = "Add photos",
            poiNoPhotosSelected = "No photos selected",
            poiPhotosHint = "You can attach up to 5 photos",
            poiPhotoLimitReached = "Maximum 5 photos per POI",
            poiPhotoReadError = "Failed to load selected photos",
            postCreateTitle = "Create Post",
            postTitleLabel = "Title",
            postDescriptionLabel = "Description",
            postAudienceLabel = "Audience",
            postAudiencePublic = "Public",
            postAudienceFriends = "Friends",
            postAudienceClub = "Club",
            postTripLabel = "Trip",
            postNoTrips = "No trips yet",
            postRouteLabel = "Route",
            postNoRoutes = "No routes yet",
            postPoisLabel = "Linked POIs",
            postNoPois = "No POIs yet",
            postCreationValidation = "Enter post title",
            photosLabel = "Photos",
            photosHint = "Add photo URLs separated by comma or new line",
            postNoPhotosSelected = "No photos selected",
            postPhotosHint = "You can attach up to 10 photos",
            postPhotoLimitReached = "Maximum 10 photos per post",
            postPhotoReadError = "Failed to load selected photos",
            noneLabel = "None",
            saveAction = "Save",
            deleteAction = "Delete",
            deleteConfirmTitle = "Delete item?",
            deleteConfirmMessage = "This action cannot be undone.",
            cardMore = "...more",
            settingsPlaceholderTitle = "Settings",
            settingsPlaceholderBody = "This section will be implemented later.",
            settingsDisplaySection = "Display",
            settingsLanguageLabel = "Language",
            settingsThemeLabel = "Appearance",
            settingsThemeLight = "Light",
            settingsThemeDark = "Dark",
            settingsThemeSystem = "Auto",
            settingsNotificationsSection = "Notifications",
            settingsPrivacySection = "Privacy",
            settingsAccountSection = "Account",
            settingsAboutSection = "About",
            settingsVersionLabel = "Version",
            wardrobeAction = "Wardrobe",
            journalAllFilter = "All",
            journalTripFilter = "Trip",
            journalStandaloneFilter = "Standalone",
            journalEmptyTitle = "No journal entries yet",
            journalEmptyBody = "Create a post or trip note to start your personal archive.",
            feedSearchPlaceholder = "Search posts",
            notificationsTitle = "Notifications",
            notificationsEmptyTitle = "No notifications yet",
            notificationsEmptyBody = "Post activity and system events will appear here.",
            tabHome = "Home",
            tabWallet = "Wallet",
            tabTrips = "Trips",
        )
        AppLanguage.RU -> AppStrings(
            appName = "Allterra",
            appTagline = "Кошелёк туриста — всё, что нужно в горах,\nв одном месте",
            appFooter = "Allterra App ©",
            loginTitle = "С возвращением",
            registerTitle = "Регистрация нового пользователя",
            registerSubtitle = "Начнем ваше путешествие",
            nameLabel = "Имя",
            emailLabel = "Email",
            passwordLabel = "Пароль",
            loginAction = "Войти",
            registerAction = "Регистрация",
            registerLink = "Регистрация",
            loginLink = "Назад ко входу",
            languageLabel = "Русский",
            loadingText = "Загружаем ваше outdoor-пространство...",
            authFieldValidation = "Заполните все обязательные поля",
            authSuccess = "Успешно. Переходим...",
            logoutAction = "Выход",
            feedHeaderUser = "UserName",
            aboutTitle = "О себе",
            aboutPlaceholder = "Люблю путешествия, хайкинг и байкпакинг",
            profileName = "User Name",
            profileAbout = "Люблю путешествия, хайкинг и байкпакинг",
            tabRoutes = "Маршруты",
            tabProfile = "Профиль",
            tabMap = "Карта",
            tabFeed = "Лента",
            tabSettings = "Настройки",
            poisTitle = "POI",
            routesTitle = "Маршруты",
            mapTitle = "Карта",
            feedTitle = "Лента",
            feedEmptyTitle = "В ленте пока нет записей",
            feedEmptyBody = "Создайте первое обновление с маршрута или обновите экран после публикаций друзей.",
            feedLoadMoreAction = "Загрузить еще",
            feedTabAll = "Всё",
            feedTabFriends = "Друзья",
            feedTabClubs = "Клубы",
            feedTabDiscover = "Discover",
            feedChipAllActivities = "Все активности",
            feedChipHike = "Хайк",
            feedChipBikepacking = "Байкпакинг",
            feedChipClimb = "Альпинизм",
            feedNearbyAuthorsLabel = "авторов рядом",
            feedOpenMapAction = "На карту",
            walletFeatureTitle = "Кошелек",
            walletFeatureDesc = "Билеты, брони",
            routesFeatureTitle = "Маршруты",
            routesFeatureDesc = "Карта, GPX, топо",
            gearFeatureTitle = "Снаряжение",
            gearFeatureDesc = "Списки сборов",
            sharingFeatureTitle = "Группа",
            sharingFeatureDesc = "Синхронизация",
            addedLabel = "Добавлено",
            updatedLabel = "Обновлено",
            importRouteTitle = "Импорт маршрута",
            importRouteBody = "Выберите источник для добавления маршрута",
            importSampleAction = "Импорт GPX",
            importGpxAction = "Импорт GPX",
            addEmptyRouteAction = "Добавить пустой маршрут",
            cancelAction = "Отмена",
            poiNewTitle = "Новая точка",
            routeNewTitle = "Новый маршрут",
            routeCreateTitle = "Добавление маршрута",
            routeTitleLabel = "Название маршрута",
            routeDescriptionLabel = "Описание",
            routeGpxLabel = "GPX файл",
            routeNoFileSelected = "Файл не выбран",
            routeImportFailed = "Не удалось прочитать GPX файл",
            routeCreationValidation = "Импортируйте валидный GPX-трек минимум с 2 точками трека",
            routeUploadingLabel = "Загрузка GPX файла...",
            routeProcessingLabel = "Обработка маршрута на сервере...",
            routePreviewTitle = "Превью маршрута",
            routeDistanceLabel = "Дистанция",
            routeDurationLabel = "Длительность",
            routePointsLabel = "Точки",
            poiCreateTitle = "Добавление POI",
            poiNameLabel = "Название POI",
            poiTypeLabel = "Тип",
            poiCreationValidation = "Введите название POI",
            poiTypeShop = "Магазин",
            poiTypeParking = "Парковка",
            poiTypeCamping = "Кемпинг",
            poiTypeWater = "Источник воды",
            poiTypeOther = "Иное",
            addPhotosAction = "Добавить фото",
            poiNoPhotosSelected = "Фото не выбраны",
            poiPhotosHint = "Можно добавить до 5 фото",
            poiPhotoLimitReached = "Максимум 5 фото на одну точку",
            poiPhotoReadError = "Не удалось загрузить выбранные фото",
            postCreateTitle = "Добавление записи",
            postTitleLabel = "Заголовок",
            postDescriptionLabel = "Описание",
            postAudienceLabel = "Аудитория",
            postAudiencePublic = "Все",
            postAudienceFriends = "Друзья",
            postAudienceClub = "Клуб",
            postTripLabel = "Выход",
            postNoTrips = "Выходов пока нет",
            postRouteLabel = "Маршрут",
            postNoRoutes = "Маршрутов пока нет",
            postPoisLabel = "Связанные POI",
            postNoPois = "POI пока нет",
            postCreationValidation = "Введите заголовок записи",
            photosLabel = "Фотографии",
            photosHint = "Укажите URL фото через запятую или с новой строки",
            postNoPhotosSelected = "Фото не выбраны",
            postPhotosHint = "Можно добавить до 10 фото",
            postPhotoLimitReached = "Максимум 10 фото на запись",
            postPhotoReadError = "Не удалось загрузить выбранные фото",
            noneLabel = "Нет",
            saveAction = "Сохранить",
            deleteAction = "Удалить",
            deleteConfirmTitle = "Удалить элемент?",
            deleteConfirmMessage = "Это действие нельзя отменить.",
            cardMore = "...подробнее",
            settingsPlaceholderTitle = "Настройки",
            settingsPlaceholderBody = "Этот раздел реализуем в следующих коммитах.",
            settingsDisplaySection = "Экран",
            settingsLanguageLabel = "Язык",
            settingsThemeLabel = "Тема",
            settingsThemeLight = "Светлая",
            settingsThemeDark = "Темная",
            settingsThemeSystem = "Системная",
            settingsNotificationsSection = "Уведомления",
            settingsPrivacySection = "Конфиденциальность",
            settingsAccountSection = "Аккаунт",
            settingsAboutSection = "О приложении",
            settingsVersionLabel = "Версия",
            wardrobeAction = "Гардероб",
            journalAllFilter = "Все",
            journalTripFilter = "С выходом",
            journalStandaloneFilter = "Отдельно",
            journalEmptyTitle = "Записей в журнале пока нет",
            journalEmptyBody = "Создайте пост или заметку к выходу, чтобы начать личный архив.",
            feedSearchPlaceholder = "Поиск по постам",
            notificationsTitle = "Уведомления",
            notificationsEmptyTitle = "Уведомлений пока нет",
            notificationsEmptyBody = "Здесь появятся события по постам и системные уведомления.",
            tabHome = "Главная",
            tabWallet = "Кошелек",
            tabTrips = "Выходы",
            onboardingTitle = "Добро пожаловать в Allterra",
            onboardingSubtitle = "Кошелек туриста для каждого выхода.",
            onboardingStartAction = "Начать",
            onboardingSkipAction = "Пропустить",
            onboardingNextAction = "Дальше",
            onboardingFinishAction = "Готово",
            onboardingWalletTitle = "Кошелек туриста",
            onboardingWalletBody = "PDF, билеты, брони и страховки в одном безопасном месте.",
            onboardingMapTitle = "Оффлайн-карты",
            onboardingMapBody = "Маршруты, точки и профиль высот готовы даже без сети.",
            onboardingGearTitle = "Снаряжение",
            onboardingGearBody = "Списки сборов, инвентарь и износ перед каждым выходом.",
            onboardingSocialTitle = "Делитесь с группой",
            onboardingSocialBody = "Координируйтесь с друзьями и держите всех в курсе.",
            dashboardGreetingPrefix = "Привет",
            dashboardGreetingBody = "Готовы к следующему приключению?",
            dashboardUpcomingTrip = "Ближайший выход",
            dashboardPackingProgress = "Сборы",
            dashboardQuickActions = "Быстрые действия",
            dashboardRecentTrips = "Недавние выходы",
            dashboardSeeAll = "Все",
            dashboardPackingAction = "Сборы",
            dashboardNewPostAction = "Новый пост",
            dashboardAddDocAction = "Документ",
            walletTitle = "Кошелек туриста",
            walletOfflineStatus = "Оффлайн",
            walletTicketsGroup = "Активные билеты",
            walletBookingsGroup = "Брони",
            walletInsuranceGroup = "Страховки",
            walletOtherGroup = "Документы",
            walletAddTitle = "Добавить в кошелек",
            walletImportPhoto = "Фото",
            walletImportEmail = "Email",
            walletImportScan = "Скан",
            walletImportManual = "Вручную",
            walletOpenPdf = "Открыть PDF",
            shareAction = "Поделиться",
            dateLabel = "Дата",
            timeLabel = "Время",
            locationLabel = "Место",
            postNewSubtitle = "в твоей ленте",
            postTypeLabel = "ТИП",
            postTypeCheckIn = "Чек-ин",
            postTypeRoute = "Маршрут",
            postTypeNote = "Заметка",
            postTypeGear = "Снаряжение",
            postPhotoUploadTitle = "Добавить фото или обложку",
            postPhotoUploadLimit = "jpg, heic · до 9 шт",
            postLocationPlaceholder = "Где ты сейчас?",
            postBodyPlaceholder = "Расскажи, как было...",
            postActivityLabel = "АКТИВНОСТЬ",
            postPublishAction = "Опубликовать",
            feedFilterTitle = "Фильтры",
            feedFilterClear = "Сбросить",
            feedPostTripLabel = "Выход",
            feedPostRouteLabel = "Маршрут",
            feedChipTrek = "Трек",
            feedChipClimbing = "Скалолазание",
            postLinkedItemLabel = "Локация",
            postNoCommentsTitle = "Пока нет комментариев",
            postNoCommentsBody = "Будьте первым, кто поделится мыслями!",
        )
        AppLanguage.PL -> AppStrings(
            appName = "Allterra",
            appTagline = "Odkrywaj, dziel sie i inspiruj aktywnym wypoczynkiem",
            appFooter = "Allterra App ©",
            loginTitle = "Witaj ponownie",
            registerTitle = "Nowa rejestracja uzytkownika",
            registerSubtitle = "Zacznijmy Twoja podroz",
            nameLabel = "Nazwa",
            emailLabel = "Email",
            passwordLabel = "Haslo",
            loginAction = "Logowanie",
            registerAction = "Rejestracja",
            registerLink = "Rejestracja",
            loginLink = "Powrot do logowania",
            languageLabel = "Polski",
            loadingText = "Ladujemy Twoj outdoor world...",
            authFieldValidation = "Uzupelnij wszystkie wymagane pola",
            authSuccess = "Sukces. Przekierowanie...",
            logoutAction = "Wyloguj",
            feedHeaderUser = "UserName",
            aboutTitle = "About",
            aboutPlaceholder = "Kocham podroze, hiking i bikepacking",
            profileName = "User Name",
            profileAbout = "Kocham podroze, hiking i bikepacking",
            tabRoutes = "Trasy",
            tabProfile = "Profil",
            tabMap = "Mapa",
            tabFeed = "Feed",
            tabSettings = "Ustawienia",
            poisTitle = "POI",
            routesTitle = "Trasy",
            mapTitle = "Mapa",
            feedTitle = "Feed",
            feedEmptyTitle = "Brak wpisow w feedzie",
            feedEmptyBody = "Dodaj pierwsza aktualizacje z trasy albo odswiez po publikacjach znajomych.",
            feedLoadMoreAction = "Wczytaj wiecej",
            feedTabAll = "Wszystko",
            feedTabFriends = "Znajomi",
            feedTabClubs = "Kluby",
            feedTabDiscover = "Discover",
            feedChipAllActivities = "Wszystkie aktywnosci",
            feedChipHike = "Hike",
            feedChipBikepacking = "Bikepacking",
            feedChipClimb = "Wspinaczka",
            feedNearbyAuthorsLabel = "autorow w poblizu",
            feedOpenMapAction = "Na mapie",
            addedLabel = "Dodano",
            updatedLabel = "Zaktualizowano",
            importRouteTitle = "Import trasy",
            importRouteBody = "Wybierz zrodlo dodania trasy",
            importSampleAction = "Import GPX",
            importGpxAction = "Import GPX",
            addEmptyRouteAction = "Dodaj pusta trase",
            cancelAction = "Anuluj",
            poiNewTitle = "Nowy POI",
            routeNewTitle = "Nowa trasa",
            routeCreateTitle = "Dodaj trase",
            routeTitleLabel = "Nazwa trasy",
            routeDescriptionLabel = "Opis",
            routeGpxLabel = "Plik GPX",
            routeNoFileSelected = "Brak wybranego pliku",
            routeImportFailed = "Nie udalo sie odczytac pliku GPX",
            routeCreationValidation = "Zaimportuj poprawny slady GPX z co najmniej 2 punktami trasy",
            routeUploadingLabel = "Przesylanie pliku GPX...",
            routeProcessingLabel = "Przetwarzanie trasy na serwerze...",
            routePreviewTitle = "Podglad trasy",
            routeDistanceLabel = "Dystans",
            routeDurationLabel = "Czas",
            routePointsLabel = "Punkty",
            poiCreateTitle = "Dodaj POI",
            poiNameLabel = "Nazwa POI",
            poiTypeLabel = "Typ",
            poiCreationValidation = "Wpisz nazwe POI",
            poiTypeShop = "Sklep",
            poiTypeParking = "Parking",
            poiTypeCamping = "Camping",
            poiTypeWater = "Zrodlo wody",
            poiTypeOther = "Inne",
            addPhotosAction = "Dodaj zdjecia",
            poiNoPhotosSelected = "Nie wybrano zdjec",
            poiPhotosHint = "Mozesz dodac maksymalnie 5 zdjec",
            poiPhotoLimitReached = "Maksymalnie 5 zdjec na POI",
            poiPhotoReadError = "Nie udalo sie zaladowac wybranych zdjec",
            postCreateTitle = "Dodaj wpis",
            postTitleLabel = "Tytul",
            postDescriptionLabel = "Opis",
            postAudienceLabel = "Odbiorcy",
            postAudiencePublic = "Publiczne",
            postAudienceFriends = "Znajomi",
            postAudienceClub = "Klub",
            postTripLabel = "Wypad",
            postNoTrips = "Brak wypadow",
            postRouteLabel = "Trasa",
            postNoRoutes = "Brak tras",
            postPoisLabel = "Powiazane POI",
            postNoPois = "Brak POI",
            postCreationValidation = "Wpisz tytul wpisu",
            photosLabel = "Zdjecia",
            photosHint = "Dodaj URL zdjec oddzielone przecinkiem lub nowa linia",
            postNoPhotosSelected = "Nie wybrano zdjec",
            postPhotosHint = "Mozesz dodac maksymalnie 10 zdjec",
            postPhotoLimitReached = "Maksymalnie 10 zdjec na wpis",
            postPhotoReadError = "Nie udalo sie zaladowac wybranych zdjec",
            noneLabel = "Brak",
            saveAction = "Zapisz",
            deleteAction = "Usun",
            deleteConfirmTitle = "Usun element?",
            deleteConfirmMessage = "Tej operacji nie mozna cofnac.",
            cardMore = "...wiecej",
            settingsPlaceholderTitle = "Ustawienia",
            settingsPlaceholderBody = "Ta sekcja bedzie gotowa w kolejnych commitach.",
            wardrobeAction = "Garderoba",
            journalAllFilter = "Wszystkie",
            journalTripFilter = "Z wypadem",
            journalStandaloneFilter = "Samodzielne",
            journalEmptyTitle = "Brak wpisow w dzienniku",
            journalEmptyBody = "Dodaj wpis lub notatke z wypadu, aby zbudowac swoje archiwum.",
            feedSearchPlaceholder = "Szukaj wpisow",
            notificationsTitle = "Powiadomienia",
            notificationsEmptyTitle = "Brak powiadomien",
            notificationsEmptyBody = "Tutaj pojawia sie aktywnosc wpisow i zdarzenia systemowe.",
            tabHome = "Start",
            tabWallet = "Portfel",
            tabTrips = "Wypady",
            onboardingTitle = "Witaj w Allterra",
            onboardingSubtitle = "Portfel turysty na kazdy wypad.",
            onboardingStartAction = "Zaczynamy",
            onboardingSkipAction = "Pomin",
            onboardingNextAction = "Dalej",
            onboardingFinishAction = "Gotowe",
            onboardingWalletTitle = "Portfel turysty",
            onboardingWalletBody = "PDF-y, bilety, rezerwacje i ubezpieczenia w jednym bezpiecznym miejscu.",
            onboardingMapTitle = "Mapy offline",
            onboardingMapBody = "Trasy, punkty i profil wysokosci gotowe bez internetu.",
            onboardingGearTitle = "Sprzet",
            onboardingGearBody = "Listy pakowania, ekwipunek i zuzycie przed kazdym wyjsciem.",
            onboardingSocialTitle = "Udostepniaj grupie",
            onboardingSocialBody = "Koordynuj ze znajomymi i trzymaj grupe na biezaco.",
            dashboardGreetingPrefix = "Czesc",
            dashboardGreetingBody = "Gotowy na kolejna przygode?",
            dashboardUpcomingTrip = "Najblizszy wypad",
            dashboardPackingProgress = "Pakowanie",
            dashboardQuickActions = "Szybkie akcje",
            dashboardRecentTrips = "Ostatnie wypady",
            dashboardSeeAll = "Wszystkie",
            dashboardPackingAction = "Pakowanie",
            dashboardNewPostAction = "Nowy wpis",
            dashboardAddDocAction = "Dokument",
            walletTitle = "Portfel turysty",
            walletOfflineStatus = "Offline",
            walletTicketsGroup = "Aktywne bilety",
            walletBookingsGroup = "Rezerwacje",
            walletInsuranceGroup = "Ubezpieczenia",
            walletOtherGroup = "Dokumenty",
            walletAddTitle = "Dodaj do portfela",
            walletImportPhoto = "Zdjecie",
            walletImportScan = "Skan",
            walletImportManual = "Recznie",
            walletOpenPdf = "Otworz PDF",
            shareAction = "Udostepnij",
            dateLabel = "Data",
            timeLabel = "Czas",
            locationLabel = "Miejsce",
            feedFilterTitle = "Filtry",
            feedFilterClear = "Wyczysc",
            feedPostTripLabel = "Wypad",
            feedPostRouteLabel = "Trasa",
            feedChipTrek = "Trek",
            feedChipClimbing = "Wspinaczka",
            postLinkedItemLabel = "Lokalizacja",
            postNoCommentsTitle = "Brak komentarzy",
            postNoCommentsBody = "Badz pierwszym, który podzieli sie swoimi myslami!",
        )
        AppLanguage.DE -> AppStrings(
            appName = "Allterra",
            appTagline = "Die Wandermappe",
            appFooter = "Allterra App ©",
            loginTitle = "Willkommen zuruck",
            registerTitle = "Registrieren",
            registerSubtitle = "Beginne deine Reise",
            nameLabel = "Name",
            emailLabel = "E-Mail",
            passwordLabel = "Passwort",
            loginAction = "Anmelden",
            registerAction = "Registrieren",
            registerLink = "Registrieren",
            loginLink = "Zuruck zur Anmeldung",
            languageLabel = "Deutsch",
            loadingText = "Deine Outdoor-Welt wird geladen...",
            authFieldValidation = "Bitte alle Pflichtfelder ausfullen",
            authSuccess = "Erfolgreich. Weiterleitung...",
            logoutAction = "Abmelden",
            feedHeaderUser = "UserName",
            aboutTitle = "Uber mich",
            aboutPlaceholder = "Reisen, Wandern und Bikepacking",
            profileName = "User Name",
            profileAbout = "Reisen, Wandern und Bikepacking",
            tabRoutes = "Routen",
            tabProfile = "Profil",
            tabMap = "Karte",
            tabFeed = "Feed",
            tabSettings = "Einstellungen",
            poisTitle = "POIs",
            routesTitle = "Routen",
            mapTitle = "Karte",
            feedTitle = "Feed",
            feedEmptyTitle = "Noch keine Beitrage im Feed",
            feedEmptyBody = "Erstelle das erste Update von unterwegs oder aktualisiere nach neuen Posts deiner Freunde.",
            feedLoadMoreAction = "Mehr laden",
            feedTabAll = "Alle",
            feedTabFriends = "Freunde",
            feedTabClubs = "Clubs",
            feedTabDiscover = "Discover",
            feedChipAllActivities = "Alle Aktivitaten",
            feedChipHike = "Hike",
            feedChipBikepacking = "Bikepacking",
            feedChipClimb = "Alpin",
            feedNearbyAuthorsLabel = "Autoren in der Nahe",
            feedOpenMapAction = "Zur Karte",
            addedLabel = "Hinzugefugt",
            updatedLabel = "Aktualisiert",
            importRouteTitle = "Route importieren",
            importRouteBody = "Quelle fur die Route auswahlen",
            importSampleAction = "GPX importieren",
            importGpxAction = "GPX importieren",
            addEmptyRouteAction = "Leere Route",
            cancelAction = "Abbrechen",
            poiNewTitle = "Neuer POI",
            routeNewTitle = "Neue Route",
            routeCreateTitle = "Route erstellen",
            routeTitleLabel = "Routentitel",
            routeDescriptionLabel = "Beschreibung",
            routeGpxLabel = "GPX-Datei",
            routeNoFileSelected = "Keine Datei ausgewahlt",
            routeImportFailed = "GPX-Datei konnte nicht gelesen werden",
            routeCreationValidation = "Importiere einen gultigen GPX-Track mit mindestens 2 Punkten",
            routeUploadingLabel = "GPX-Datei wird hochgeladen...",
            routeProcessingLabel = "Route wird verarbeitet...",
            routePreviewTitle = "Routenvorschau",
            routeDistanceLabel = "Distanz",
            routeDurationLabel = "Dauer",
            routePointsLabel = "Punkte",
            poiCreateTitle = "POI erstellen",
            poiNameLabel = "POI-Name",
            poiTypeLabel = "Typ",
            poiCreationValidation = "POI-Name eingeben",
            poiTypeShop = "Shop",
            poiTypeParking = "Parkplatz",
            poiTypeCamping = "Camping",
            poiTypeWater = "Wasserquelle",
            poiTypeOther = "Andere",
            addPhotosAction = "Fotos hinzufugen",
            poiNoPhotosSelected = "Keine Fotos ausgewahlt",
            poiPhotosHint = "Bis zu 5 Fotos moglich",
            poiPhotoLimitReached = "Maximal 5 Fotos pro POI",
            poiPhotoReadError = "Fotos konnten nicht geladen werden",
            postCreateTitle = "Beitrag erstellen",
            postTitleLabel = "Titel",
            postDescriptionLabel = "Beschreibung",
            postAudienceLabel = "Sichtbarkeit",
            postAudiencePublic = "Offentlich",
            postAudienceFriends = "Freunde",
            postAudienceClub = "Club",
            postTripLabel = "Tour",
            postNoTrips = "Noch keine Touren",
            postRouteLabel = "Route",
            postNoRoutes = "Noch keine Routen",
            postPoisLabel = "Verknupfte POIs",
            postNoPois = "Noch keine POIs",
            postCreationValidation = "Titel eingeben",
            photosLabel = "Fotos",
            photosHint = "Foto-URLs mit Komma oder Zeilenumbruch trennen",
            postNoPhotosSelected = "Keine Fotos ausgewahlt",
            postPhotosHint = "Bis zu 10 Fotos moglich",
            postPhotoLimitReached = "Maximal 10 Fotos pro Beitrag",
            postPhotoReadError = "Fotos konnten nicht geladen werden",
            noneLabel = "Keine",
            saveAction = "Speichern",
            deleteAction = "Loschen",
            deleteConfirmTitle = "Element loschen?",
            deleteConfirmMessage = "Diese Aktion kann nicht ruckgangig gemacht werden.",
            cardMore = "...mehr",
            settingsPlaceholderTitle = "Einstellungen",
            settingsPlaceholderBody = "Dieser Bereich wird spater umgesetzt.",
            wardrobeAction = "Ausrustung",
            journalAllFilter = "Alle",
            journalTripFilter = "Mit Tour",
            journalStandaloneFilter = "Einzeln",
            journalEmptyTitle = "Noch keine Eintrage im Journal",
            journalEmptyBody = "Erstelle einen Beitrag oder eine Tour-Notiz fur dein personliches Archiv.",
            feedSearchPlaceholder = "Beitrage suchen",
            notificationsTitle = "Benachrichtigungen",
            notificationsEmptyTitle = "Noch keine Benachrichtigungen",
            notificationsEmptyBody = "Aktivitat zu Beitragen und Systemereignisse erscheinen hier.",
            tabHome = "Start",
            tabWallet = "Wallet",
            tabTrips = "Touren",
            onboardingTitle = "Willkommen bei Allterra",
            onboardingSubtitle = "Die Wandermappe fur jede Tour.",
            onboardingStartAction = "Loslegen",
            onboardingSkipAction = "Uberspringen",
            onboardingNextAction = "Weiter",
            onboardingFinishAction = "Fertig",
            onboardingWalletTitle = "Reise-Wallet",
            onboardingWalletBody = "PDFs, Tickets, Buchungen und Versicherungen an einem sicheren Ort.",
            onboardingMapTitle = "Offline-Karten",
            onboardingMapBody = "Routen, Wegpunkte und Hohenprofile bleiben unterwegs verfugbar.",
            onboardingGearTitle = "Ausrustung",
            onboardingGearBody = "Packlisten, Inventar und Verschleiss vor jeder Tour im Blick.",
            onboardingSocialTitle = "Mit Gruppe teilen",
            onboardingSocialBody = "Koordiniere Freunde und halte alle synchron.",
            dashboardGreetingPrefix = "Hallo",
            dashboardGreetingBody = "Bereit fur das nachste Abenteuer?",
            dashboardUpcomingTrip = "Nachste Tour",
            dashboardPackingProgress = "Packfortschritt",
            dashboardQuickActions = "Schnellaktionen",
            dashboardRecentTrips = "Letzte Touren",
            dashboardSeeAll = "Alle",
            dashboardPackingAction = "Packen",
            dashboardNewPostAction = "Neuer Post",
            dashboardAddDocAction = "Dokument",
            walletTitle = "Reise-Wallet",
            walletOfflineStatus = "Offline",
            walletTicketsGroup = "Aktive Tickets",
            walletBookingsGroup = "Buchungen",
            walletInsuranceGroup = "Versicherungen",
            walletOtherGroup = "Dokumente",
            walletAddTitle = "Zur Wallet hinzufugen",
            walletImportPhoto = "Foto",
            walletImportScan = "Scan",
            walletImportManual = "Manuell",
            walletOpenPdf = "PDF offnen",
            shareAction = "Teilen",
            dateLabel = "Datum",
            timeLabel = "Zeit",
            locationLabel = "Ort",
            feedFilterTitle = "Filter",
            feedFilterClear = "Loschen",
            feedPostTripLabel = "Ausflug",
            feedPostRouteLabel = "Route",
            feedChipTrek = "Trekking",
            feedChipClimbing = "Klettern",
            postLinkedItemLabel = "Standort",
            postNoCommentsTitle = "Noch keine Kommentare",
            postNoCommentsBody = "Sei der Erste, der seine Gedanken teilt!",
        )
    }
}
