package com.allterra.presentation.localization

import com.allterra.domain.model.AppLanguage

data class AppStrings(
    val appName: String,
    val appTagline: String,
    val appFooter: String,
    val loginTitle: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val nameLabel: String,
    val emailLabel: String,
    val passwordLabel: String,
    val loginAction: String,
    val registerAction: String,
    val registerLink: String,
    val loginLink: String,
    val languageLabel: String,
    val loadingText: String,
    val authFieldValidation: String,
    val authSuccess: String,
    val logoutAction: String,
    val feedHeaderUser: String,
    val aboutTitle: String,
    val aboutPlaceholder: String,
    val profileName: String,
    val profileAbout: String,
    val tabRoutes: String,
    val tabProfile: String,
    val tabMap: String,
    val tabFeed: String,
    val tabSettings: String,
    val poisTitle: String,
    val routesTitle: String,
    val mapTitle: String,
    val feedTitle: String,
    val addedLabel: String,
    val updatedLabel: String,
    val importRouteTitle: String,
    val importRouteBody: String,
    val importSampleAction: String,
    val importGpxAction: String,
    val addEmptyRouteAction: String,
    val cancelAction: String,
    val poiNewTitle: String,
    val routeNewTitle: String,
    val routeCreateTitle: String,
    val routeTitleLabel: String,
    val routeDescriptionLabel: String,
    val routeGpxLabel: String,
    val routeNoFileSelected: String,
    val routeImportFailed: String,
    val routeCreationValidation: String,
    val routeUploadingLabel: String,
    val routeProcessingLabel: String,
    val routePreviewTitle: String,
    val routeDistanceLabel: String,
    val routeDurationLabel: String,
    val routePointsLabel: String,
    val poiCreateTitle: String,
    val poiNameLabel: String,
    val poiTypeLabel: String,
    val poiCreationValidation: String,
    val poiTypeShop: String,
    val poiTypeParking: String,
    val poiTypeCamping: String,
    val poiTypeWater: String,
    val poiTypeOther: String,
    val addPhotosAction: String,
    val poiNoPhotosSelected: String,
    val poiPhotosHint: String,
    val poiPhotoLimitReached: String,
    val poiPhotoReadError: String,
    val postCreateTitle: String,
    val postTitleLabel: String,
    val postDescriptionLabel: String,
    val postRouteLabel: String,
    val postNoRoutes: String,
    val postPoisLabel: String,
    val postNoPois: String,
    val postCreationValidation: String,
    val photosLabel: String,
    val photosHint: String,
    val postNoPhotosSelected: String,
    val postPhotosHint: String,
    val postPhotoLimitReached: String,
    val postPhotoReadError: String,
    val noneLabel: String,
    val saveAction: String,
    val deleteAction: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val cardMore: String,
    val settingsPlaceholderTitle: String,
    val settingsPlaceholderBody: String,
    val wardrobeAction: String,
)

fun stringsFor(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.EN -> AppStrings(
            appName = "Allterra",
            appTagline = "Explore, share, and inspire outdoor stories",
            appFooter = "Allterra App ©",
            loginTitle = "Welcome back",
            registerTitle = "New User Registration",
            registerSubtitle = "Let's start your journey",
            nameLabel = "Name",
            emailLabel = "Email",
            passwordLabel = "Password",
            loginAction = "Login",
            registerAction = "Register",
            registerLink = "Register",
            loginLink = "Back to login",
            languageLabel = "English",
            loadingText = "Loading your outdoor world...",
            authFieldValidation = "Fill all required fields",
            authSuccess = "Success. Redirecting...",
            logoutAction = "Logout",
            feedHeaderUser = "UserName",
            aboutTitle = "About",
            aboutPlaceholder = "Love travel, hiking and bikepacking",
            profileName = "User Name",
            profileAbout = "Love travel, hiking and bikepacking",
            tabRoutes = "Routes",
            tabProfile = "Profile",
            tabMap = "Map",
            tabFeed = "Feed",
            tabSettings = "Settings",
            poisTitle = "POIs",
            routesTitle = "Routes",
            mapTitle = "Map",
            feedTitle = "Feed",
            addedLabel = "Added",
            updatedLabel = "Updated",
            importRouteTitle = "Import Route",
            importRouteBody = "Choose a source to add route into your list",
            importSampleAction = "Import GPX",
            importGpxAction = "Import GPX",
            addEmptyRouteAction = "Add empty route",
            cancelAction = "Cancel",
            poiNewTitle = "New POI",
            routeNewTitle = "New Route",
            routeCreateTitle = "Create Route",
            routeTitleLabel = "Route title",
            routeDescriptionLabel = "Description",
            routeGpxLabel = "GPX file",
            routeNoFileSelected = "No file selected",
            routeImportFailed = "Failed to read GPX file",
            routeCreationValidation = "Import a valid GPX track with at least 2 track points",
            routeUploadingLabel = "Uploading GPX file...",
            routeProcessingLabel = "Parsing route on server...",
            routePreviewTitle = "Route preview",
            routeDistanceLabel = "Distance",
            routeDurationLabel = "Duration",
            routePointsLabel = "Points",
            poiCreateTitle = "Create POI",
            poiNameLabel = "POI name",
            poiTypeLabel = "Type",
            poiCreationValidation = "Enter POI name",
            poiTypeShop = "Shop",
            poiTypeParking = "Parking",
            poiTypeCamping = "Camping",
            poiTypeWater = "Water source",
            poiTypeOther = "Other",
            addPhotosAction = "Add photos",
            poiNoPhotosSelected = "No photos selected",
            poiPhotosHint = "You can attach up to 5 photos",
            poiPhotoLimitReached = "Maximum 5 photos per POI",
            poiPhotoReadError = "Failed to load selected photos",
            postCreateTitle = "Create Post",
            postTitleLabel = "Title",
            postDescriptionLabel = "Description",
            postRouteLabel = "Route",
            postNoRoutes = "No routes yet",
            postPoisLabel = "Linked POIs",
            postNoPois = "No POIs yet",
            postCreationValidation = "Enter post title",
            photosLabel = "Photos",
            photosHint = "Add photo URLs separated by comma or new line",
            postNoPhotosSelected = "No photos selected",
            postPhotosHint = "You can attach up to 10 photos",
            postPhotoLimitReached = "Maximum 10 photos per post",
            postPhotoReadError = "Failed to load selected photos",
            noneLabel = "None",
            saveAction = "Save",
            deleteAction = "Delete",
            deleteConfirmTitle = "Delete item?",
            deleteConfirmMessage = "This action cannot be undone.",
            cardMore = "...more",
            settingsPlaceholderTitle = "Settings",
            settingsPlaceholderBody = "This section will be implemented later.",
            wardrobeAction = "Wardrobe",
        )
        AppLanguage.RU -> AppStrings(
            appName = "Allterra",
            appTagline = "Исследуй, делись и вдохновляй активным отдыхом",
            appFooter = "Allterra App ©",
            loginTitle = "С возвращением",
            registerTitle = "Регистрация нового пользователя",
            registerSubtitle = "Начнем ваше путешествие",
            nameLabel = "Имя",
            emailLabel = "Email",
            passwordLabel = "Пароль",
            loginAction = "Войти",
            registerAction = "Регистрация",
            registerLink = "Регистрация",
            loginLink = "Назад ко входу",
            languageLabel = "Русский",
            loadingText = "Загружаем ваше outdoor-пространство...",
            authFieldValidation = "Заполните все обязательные поля",
            authSuccess = "Успешно. Переходим...",
            logoutAction = "Выход",
            feedHeaderUser = "UserName",
            aboutTitle = "О себе",
            aboutPlaceholder = "Люблю путешествия, хайкинг и байкпакинг",
            profileName = "User Name",
            profileAbout = "Люблю путешествия, хайкинг и байкпакинг",
            tabRoutes = "Маршруты",
            tabProfile = "Профиль",
            tabMap = "Карта",
            tabFeed = "Лента",
            tabSettings = "Настройки",
            poisTitle = "POI",
            routesTitle = "Маршруты",
            mapTitle = "Карта",
            feedTitle = "Лента",
            addedLabel = "Добавлено",
            updatedLabel = "Обновлено",
            importRouteTitle = "Импорт маршрута",
            importRouteBody = "Выберите источник для добавления маршрута",
            importSampleAction = "Импорт GPX",
            importGpxAction = "Импорт GPX",
            addEmptyRouteAction = "Добавить пустой маршрут",
            cancelAction = "Отмена",
            poiNewTitle = "Новая точка",
            routeNewTitle = "Новый маршрут",
            routeCreateTitle = "Добавление маршрута",
            routeTitleLabel = "Название маршрута",
            routeDescriptionLabel = "Описание",
            routeGpxLabel = "GPX файл",
            routeNoFileSelected = "Файл не выбран",
            routeImportFailed = "Не удалось прочитать GPX файл",
            routeCreationValidation = "Импортируйте валидный GPX-трек минимум с 2 точками трека",
            routeUploadingLabel = "Загрузка GPX файла...",
            routeProcessingLabel = "Обработка маршрута на сервере...",
            routePreviewTitle = "Превью маршрута",
            routeDistanceLabel = "Дистанция",
            routeDurationLabel = "Длительность",
            routePointsLabel = "Точки",
            poiCreateTitle = "Добавление POI",
            poiNameLabel = "Название POI",
            poiTypeLabel = "Тип",
            poiCreationValidation = "Введите название POI",
            poiTypeShop = "Магазин",
            poiTypeParking = "Парковка",
            poiTypeCamping = "Кемпинг",
            poiTypeWater = "Источник воды",
            poiTypeOther = "Иное",
            addPhotosAction = "Добавить фото",
            poiNoPhotosSelected = "Фото не выбраны",
            poiPhotosHint = "Можно добавить до 5 фото",
            poiPhotoLimitReached = "Максимум 5 фото на одну точку",
            poiPhotoReadError = "Не удалось загрузить выбранные фото",
            postCreateTitle = "Добавление записи",
            postTitleLabel = "Заголовок",
            postDescriptionLabel = "Описание",
            postRouteLabel = "Маршрут",
            postNoRoutes = "Маршрутов пока нет",
            postPoisLabel = "Связанные POI",
            postNoPois = "POI пока нет",
            postCreationValidation = "Введите заголовок записи",
            photosLabel = "Фотографии",
            photosHint = "Укажите URL фото через запятую или с новой строки",
            postNoPhotosSelected = "Фото не выбраны",
            postPhotosHint = "Можно добавить до 10 фото",
            postPhotoLimitReached = "Максимум 10 фото на запись",
            postPhotoReadError = "Не удалось загрузить выбранные фото",
            noneLabel = "Нет",
            saveAction = "Сохранить",
            deleteAction = "Удалить",
            deleteConfirmTitle = "Удалить элемент?",
            deleteConfirmMessage = "Это действие нельзя отменить.",
            cardMore = "...подробнее",
            settingsPlaceholderTitle = "Настройки",
            settingsPlaceholderBody = "Этот раздел реализуем в следующих коммитах.",
            wardrobeAction = "Гардероб",
        )
        AppLanguage.PL -> AppStrings(
            appName = "Allterra",
            appTagline = "Odkrywaj, dziel sie i inspiruj aktywnym wypoczynkiem",
            appFooter = "Allterra App ©",
            loginTitle = "Witaj ponownie",
            registerTitle = "Nowa rejestracja uzytkownika",
            registerSubtitle = "Zacznijmy Twoja podroz",
            nameLabel = "Nazwa",
            emailLabel = "Email",
            passwordLabel = "Haslo",
            loginAction = "Logowanie",
            registerAction = "Rejestracja",
            registerLink = "Rejestracja",
            loginLink = "Powrot do logowania",
            languageLabel = "Polski",
            loadingText = "Ladujemy Twoj outdoor world...",
            authFieldValidation = "Uzupelnij wszystkie wymagane pola",
            authSuccess = "Sukces. Przekierowanie...",
            logoutAction = "Wyloguj",
            feedHeaderUser = "UserName",
            aboutTitle = "About",
            aboutPlaceholder = "Kocham podroze, hiking i bikepacking",
            profileName = "User Name",
            profileAbout = "Kocham podroze, hiking i bikepacking",
            tabRoutes = "Trasy",
            tabProfile = "Profil",
            tabMap = "Mapa",
            tabFeed = "Feed",
            tabSettings = "Ustawienia",
            poisTitle = "POI",
            routesTitle = "Trasy",
            mapTitle = "Mapa",
            feedTitle = "Feed",
            addedLabel = "Dodano",
            updatedLabel = "Zaktualizowano",
            importRouteTitle = "Import trasy",
            importRouteBody = "Wybierz zrodlo dodania trasy",
            importSampleAction = "Import GPX",
            importGpxAction = "Import GPX",
            addEmptyRouteAction = "Dodaj pusta trase",
            cancelAction = "Anuluj",
            poiNewTitle = "Nowy POI",
            routeNewTitle = "Nowa trasa",
            routeCreateTitle = "Dodaj trase",
            routeTitleLabel = "Nazwa trasy",
            routeDescriptionLabel = "Opis",
            routeGpxLabel = "Plik GPX",
            routeNoFileSelected = "Brak wybranego pliku",
            routeImportFailed = "Nie udalo sie odczytac pliku GPX",
            routeCreationValidation = "Zaimportuj poprawny slady GPX z co najmniej 2 punktami trasy",
            routeUploadingLabel = "Przesylanie pliku GPX...",
            routeProcessingLabel = "Przetwarzanie trasy na serwerze...",
            routePreviewTitle = "Podglad trasy",
            routeDistanceLabel = "Dystans",
            routeDurationLabel = "Czas",
            routePointsLabel = "Punkty",
            poiCreateTitle = "Dodaj POI",
            poiNameLabel = "Nazwa POI",
            poiTypeLabel = "Typ",
            poiCreationValidation = "Wpisz nazwe POI",
            poiTypeShop = "Sklep",
            poiTypeParking = "Parking",
            poiTypeCamping = "Camping",
            poiTypeWater = "Zrodlo wody",
            poiTypeOther = "Inne",
            addPhotosAction = "Dodaj zdjecia",
            poiNoPhotosSelected = "Nie wybrano zdjec",
            poiPhotosHint = "Mozesz dodac maksymalnie 5 zdjec",
            poiPhotoLimitReached = "Maksymalnie 5 zdjec na POI",
            poiPhotoReadError = "Nie udalo sie zaladowac wybranych zdjec",
            postCreateTitle = "Dodaj wpis",
            postTitleLabel = "Tytul",
            postDescriptionLabel = "Opis",
            postRouteLabel = "Trasa",
            postNoRoutes = "Brak tras",
            postPoisLabel = "Powiazane POI",
            postNoPois = "Brak POI",
            postCreationValidation = "Wpisz tytul wpisu",
            photosLabel = "Zdjecia",
            photosHint = "Dodaj URL zdjec oddzielone przecinkiem lub nowa linia",
            postNoPhotosSelected = "Nie wybrano zdjec",
            postPhotosHint = "Mozesz dodac maksymalnie 10 zdjec",
            postPhotoLimitReached = "Maksymalnie 10 zdjec na wpis",
            postPhotoReadError = "Nie udalo sie zaladowac wybranych zdjec",
            noneLabel = "Brak",
            saveAction = "Zapisz",
            deleteAction = "Usun",
            deleteConfirmTitle = "Usun element?",
            deleteConfirmMessage = "Tej operacji nie mozna cofnac.",
            cardMore = "...wiecej",
            settingsPlaceholderTitle = "Ustawienia",
            settingsPlaceholderBody = "Ta sekcja bedzie gotowa w kolejnych commitach.",
            wardrobeAction = "Garderoba",
        )
    }
}
